In [8]:
# Visualising the data
# • Plot a probability density histogram for each type of stimulus. This height of each bar
# should be the proportion of responses divided by the width of the column.

import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import glob
%matplotlib inline
plt.rcParams['figure.figsize'] = (20,10)

# Load the data
data_path= "Data/Part_2/"
dfs = []
for file in glob.glob('Data/Part_2/*.txt'):
  dfs.append(pd.DataFrame(np.loadtxt(file)))
df_all = pd.concat(dfs)

In [9]:
# The first row of the array contains response counts for the auditory stimuli. The columns of
# the first row indicate the specific auditory stimulus ranging from very similar to a ’b’ in the
# first column to very similar to a ’d’ in the last column. Likewise, the second row contains
# response counts to the visual stimulus ranging from very similar to a ’b’ to very similar to a
# ’d’. Rows 3-7 contains response counts for the audiovisual stimuli. Rows indicate the visual
# component of the stimulus ranging from very similar to a ’b’ (row 3) to very similar to a ’d’
# (row 7). Columns indicate the auditory component of the stimulus ranging from very similar
# to a ’b’ (column 1) to very similar to a ’d’ (column 5).
# df_all

In [10]:
# split df_all into 5 dfs
df_1 = df_all.iloc[0:7,0:5]
df_2 = df_all.iloc[7:14,0:5]
df_3 = df_all.iloc[14:21,0:5]
df_4 = df_all.iloc[21:28,0:5]
df_5 = df_all.iloc[28:35,0:5]



In [ ]:
# fit the early strong fusion model

def early_strong_fusion(data):
    # our code here
    return model

  


In [12]:
df_1

0     1     2     3     4
0   0.0   2.0   4.0  24.0  24.0
1   0.0  17.0  24.0  24.0  24.0
2   0.0   0.0   0.0  10.0  14.0
3   4.0   8.0   7.0  20.0  22.0
4   9.0  15.0  19.0  24.0  24.0
5  14.0  17.0  22.0  24.0  24.0
6  14.0  19.0  23.0  24.0  24.0

In [20]:
from scipy.stats import norm

means_ini = [1,2,3,4,5]
# means_ini = [1,2,3,4,5]
sigma_a_ini = df_1[0].std(axis=0).mean()
sigma_v_ini = df_1[1].std(axis=0).mean()

In [36]:
# calculate the combined distributions
def combined_distributions(means_est, sigma_a_ini, sigma_v_ini, data):
    w_a = (sigma_v_ini)**2 / ((sigma_v_ini)**2 + (sigma_a_ini)**2)
    
    # 5 by 5 matrix of 0 
    means_av_matrix= np.zeros((5,5))
    print(means_av_matrix)
    # for i in range(5):
    #     for j in range(5):
    #         mean_av = w_a * (means_est[i]) + (1 - w_a) * (means_est[j+2])
    #         np.append(means_av_matrix[i,j], mean_av, axis=0)
    # sigma_av = ((sigma_a_ini)**2 * (sigma_v_ini)**2) / ((sigma_a_ini)**2 + (sigma_v_ini)**2)


    # return [means_av_matrix, sigma_av] 
    return means_av_matrix

In [37]:
combined_distributions(means_ini, sigma_a_ini, sigma_v_ini, df_1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [38]:
# use the binomial pdf with the normal cdf inside 
# look at the psycometric function for the first assignment homework 
err - stats.binomial.pdf(data0[i], loc=means[i], scale=scale[i]).sum() 


NameError: name 'means_av_matrix' is not defined

In [ ]:
# fit an early Bayesian Causal Inference model (BCI)

def early_BCI(data):
    # our code here
    return model

###### is this just the same as we did in part 1? The BCI model? ######